### ISSUE TITLE
Standardize repository

### ISSUE THREAD

**Issue by plfiorini** [liri-project/liri-text#15]
Make AUTHORS.md and README.md consistent with other repository and add a develop branch for development.

**Comment by Aldrog** [comment]
@plfiorini yep, consistency is important.

You use master branch for the latest release, don't you? I'm curious why to make it this way when there're tags which serve better for this matter.

I don't propose any change, just want to understand the motivation behind this decision.

**Comment by plfiorini** [comment]
It's the git flow development model and it is better explained here: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by Aldrog** [comment]
OK, got it. Thanks :slightly_smiling_face:

**Comment by Aldrog** [comment]
It seems good now. I'm not going to create a feature branch for syntax highlighting because it's already in a half working (and half broken) state in develop.
