### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by M1cha** [liri-project/liri-text#17]
I'd expect a simple text editor like this to start instantly(<300ms).
Instead, it takes 2-3s. Would be cool to see come improvements there.

**Comment by Aldrog** [comment]
Building a languages DB can take a while if you don't have an SSD.
It should be done in a separate thread for sure.

**Comment by M1cha** [comment]
I have an SSD :)
why do you need to build it on every start? can't it be shipped/cached?

**Comment by Aldrog** [comment]
It doesn't get rebuilt completely; it's only updated on second+ launches, but it still needs all language metadata to be parsed.
This is required because user can add additional languages or modify old ones.

btw it's a bit strange it takes so long with SSD. On my PC startup takes about half a second.

**Comment by M1cha** [comment]
I've just copied the application itself to /tmp and it took the same time(I guess you're storing the db in ~ ? )

this is the output:
inotify_add_watch("/usr/local/share/liri-text/language-specs/") failed: "No such file or directory"
qml: start page completed
qml: app complete

it takes 2s to show 'inotify_add_watch'. then it takes 500ms for the other two messages to appear. when 'qml: app complete' is shown, the app opens up instantly.

**Comment by Aldrog** [comment]
It looks for languages in `/usr/share/gtksourceview-3.0/language-specs/` and `$INSTALLATION_PREFIX/share/liri-text/language-specs/`, but there're no languages bundled with Text ATM, so only first one is actually used.
db is stored under standard user data folder (`~/.local/share/liri-project/liri-text/` in Linux)

**Comment by M1cha** [comment]
using strace I can confirm that alot of time is spent building the db.
I can also see that you're running tons of open/stat/close/fcntl/... operations per second on languages.db and languages.db-journal.

Maybe that's the place to look for improvements?

**Comment by Aldrog** [comment]
hmm.. I have only one database connection open for the whole application runtime. It must be something about how QSqlDatabase or SQLite work.

Anyway, I think simply running this in background will be a decent solution.
